version: '3.8'
services:
  api:
    image: node:lts
    container_name: 'test-proxy-api'
    entrypoint: ['node', '/app/server/index.js']
    volumes:
      - ./:/app
    networks:
      - tomenet

  server:
    image: 'nginx:stable'
    container_name: 'test-proxy-server'
    ports:
      - 81:80
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/static/:/usr/share/nginx/html
    networks:
      - tomenet
    depends_on:
      - api

  client:
    image: nginx:stable
    container_name: test-proxy-client
    ports:
      - 82:80
    volumes:
      - ./client/static/:/usr/share/nginx/html/
    networks:
      - tomenet

networks:
  tomenet:
    driver: bridge
